---
sidebar: sidebar 
permalink: task_dc_emc_unisphere_rest.html 
keywords: data collector, Unisphere, EMC 
summary: Configurar el recopilador de datos Unisphere DE Dell EMC. 
---
= Configurar el recopilador de datos Unisphere DE Dell EMC
:allow-uri-read: 


[role="lead"]
Este recopilador de datos adquiere los datos de inventario y rendimiento de Unisphere de Dell EMC para sistemas de gestión PowerMax / Vmax 3.

Tenga en cuenta que Dell/EMC no introdujo estadísticas por volumen hasta Unisphere 10.0. Este recopilador de datos admite 9.2.0+, pero no podrá recopilar estadísticas de volumen, ya que no existen.

Una instancia de Unisphere para Vmax/PowerMax puede estar gestionando una o más matrices de almacenamiento Symmetrix 3 o superiores. De forma predeterminada, este recopilador intenta descubrir todas ellas.

Para la configuración, el recopilador de datos requiere una dirección IP/FQDN del servidor Unisphere, conectividad TCP al puerto 8443 y un nombre de usuario y contraseña.



== Requisitos

* Una dirección IP/Nombre de dominio completo del servidor Unisphere
* Nombre de usuario y contraseña
* Puerto 8443.




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP del servidor Unisphere | Dirección IP o nombre de dominio completo del servidor Unisphere 


| Unisphere Port | El valor predeterminado es 8443 


| Nombre de usuario | Nombre de usuario del servidor Unisphere 


| Contraseña | Contraseña utilizada para el servidor Unisphere 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (mín.) | El valor predeterminado es 40 minutos. 


| Intervalo de sondeo de rendimiento (s) | Intervalo entre sondeos de rendimiento. 


| Elija "excluir" o "incluir" para especificar una lista | Especifique si desea incluir o excluir máquinas virtuales 


| Lista de dispositivos de filtro de inventario | Lista de equipos virtuales que se van a filtrar (separados por comas o separados por punto y coma si se utiliza la coma en el valor) para el filtrado 


| Intervalo de sondeo de rendimiento Unisphere (s) | El valor predeterminado es 300 segundos 
|===


== Resolución de problemas

Algunas cosas para intentar si tiene problemas con este recopilador de datos:



=== Inventario

[cols="2*"]
|===
| Problema: | Pruebe lo siguiente: 


| Error: Error en la autenticación del usuario. | Asegúrese de que sus credenciales para este dispositivo son correctas. 
|===
Puede encontrar información adicional en link:concept_requesting_support.html["Soporte técnico"] o en la link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matriz de compatibilidad de recopilador de datos"].
