---
sidebar: sidebar 
permalink: task_troubleshooting_general_problems.html 
summary: Consejos generales para la solución de problemas de Cloud Insights. 
keywords: troubleshooting, problems, browser, login, log in, accessing, access to, Trident, qtree, quota 
---
= Solución de problemas generales de Cloud Insights
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Aquí encontrará sugerencias para la solución de problemas de Cloud Insights.

Consulte también link:task_troubleshooting_linux_acquisition_unit_problems.html["Solución de problemas de la unidad de adquisición de Linux"] y.. link:task_troubleshooting_windows_acquisition_unit_problems.html["Solución de problemas de la unidad de adquisición de Windows"].



== Problemas de inicio de sesión

|===
| *Problema:* | *Pruebe esto:* 


| Cloud Insights cierra sesión cada 5 minutos | 396149d67edd166e53b49c38f4b707ba 


| e4ff2e59dd571d2bbd5a906b6fad2546 | a9a216fbb1fb9d774e7cedfcf74c00cf 


| Me invité a Cloud Insights pero tengo un mensaje "no autorizado". | 199017f1d912993f091b6b969d3442ad 


| 176f8c6fa466059df49f2717c021d306 | 7a8624fb56224e907698f45ef2e4cc47 


| Se cerró la sesión automáticamente después de varios días. | ed6e79e2f9b9c201ed834c6efeb7f356 


| Recibo un mensaje de error que indica que no se ha autorizado el inicio de sesión. | acf29dcaa06698c29122cba5402e3145 


| Otros errores de inicio de sesión | Pruebe el modo Incognito en Chrome, o borre el historial del navegador, las cookies y la caché. Pruebe con un perfil de navegador diferente (por ejemplo, Chrome - add person). 
|===


== Otros temas

|===


| *Pregunta:* | *Respuesta:* 


| Las cuotas físicas de mis qtrees se muestran correctamente en las consultas, pero mis cuotas flexibles se muestran como la capacidad total del volumen. ¿Es correcto? | Solo las cuotas estrictas (se establecen manualmente o se establecen mediante Trident) se mostrarán como las cuotas establecidas; si no se especifican cuotas duras, la capacidad de qtree será la capacidad de volumen interno. 


| Se configuran manualmente tanto una cuota blanda como una estricta en el mismo qtree, pero la capacidad total que muestra es la cuota rígida; ¿es correcto? | Sí, si se especifica una cuota estricta, esta se mostrará como la capacidad total. 


| Al introducir una hora de programación de un informe Cognos, a veces termino con una “m” extra en la hora programada. Por ejemplo, si escribo la hora como “02:15 PM”, puede agregar un carácter adicional: “02:15 PMM” (o PMM). Cuando hago clic afuera, cambia a “2:15 AM”.

Puedo guardar el informe, pero cuando vuelvo a abrir el informe guardado, la hora de programación aparece como AM (es decir, por la mañana), independientemente de si he introducido AM o PM en la hora programada. | Vuelva a introducir la hora programada, teniendo cuidado de no introducir los caracteres AM o PM completos; basta con escribir A para AM o P para PM. Si no se muestra el carácter adicional, la hora de programación se establecerá correctamente. 
|===


== Recursos

Se pueden encontrar consejos adicionales para la solución de problemas en la link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Insights["Base de conocimientos de NetApp"] (se requiere inicio de sesión de soporte).

Puede encontrar información adicional de soporte en Cloud Insights link:concept_requesting_support.html["Soporte técnico"] página.

Si dispone de una suscripción activa a Cloud Insights, puede utilizar estas opciones de soporte:

link:https://www.netapp.com/us/contact-us/support.aspx["Teléfono"]
link:https://mysupport.netapp.com/site/cases/mine/create?serialNumber=95001014387268156333["Ticket de soporte"]

Para obtener más información, consulte https://docs.netapp.com/us-en/cloudinsights/concept_requesting_support.html["Documentación de soporte de Cloud Insights"].
