---
sidebar: sidebar 
permalink: task_dc_na_ontap_rest.html 
keywords: data collector, ontap, ontap, CDOT, REST 
summary: Recopilador de DATOS REST DE ONTAP 
---
= Recopilador de DATOS REST DE NetApp ONTAP
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Este recopilador de datos adquiere inventario, registros de EMS y datos de rendimiento de sistemas de almacenamiento que ejecutan ONTAP 9.14.1 y posteriores mediante llamadas de API DE REST. Para los sistemas ONTAP en versiones anteriores, utilice el tipo de recopilador «Software de gestión de datos NetApp ONTAP» basado en ZAPI.


NOTE: El recopilador REST DE ONTAP puede usarse como reemplazo del recopilador basado en ONTAPI anterior. Como tal, puede haber diferencias en las métricas que se recopilan o informan. Para obtener más información sobre las diferencias entre ONTAPI y REST, consulte la link:https://docs.netapp.com/us-en/ontap-restmap-9141/index.html["Asignación de ONTAPI a REST DE ONTAP 9.14.1"] documentación.



== Migración

Para migrar desde un recopilador de datos de ONTAP (ontapi) anterior al recopilador de REST DE ONTAP más reciente, haga lo siguiente:

. Agregar Recopilador REST, introduciendo el mismo usuario/permiso/etc. tenías para el coleccionista anterior.
. Pausar el recopilador anterior.
. Deje que el sistema recopile datos durante ~30 minutos. Ignore cualquier rareza de datos durante este tiempo.
. Después del período de descanso, verá una continuación estable de los datos en el recolector de RESTO.




== Terminología

Cloud Insights adquiere datos de inventario, registros y rendimiento del recopilador de datos de ONTAP. Para cada tipo de activo adquirido, se muestra la terminología más común utilizada para el activo. Al ver o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Plazo del proveedor/modelo | Término de Cloud Insights 


| Disco | Disco 


| Grupo RAID | Grupo de discos 


| Clúster | Reducida 


| Nodo | Nodo de almacenamiento 


| Agregado | Pool de almacenamiento 


| LUN | Volumen 


| Volumen | Volumen interno 


| Máquina virtual de almacenamiento/Vserver | Máquina virtual de almacenamiento 
|===


== Terminología de gestión de datos ONTAP

Los siguientes términos se aplican a objetos o referencias que puede encontrar en las páginas de destino de activos de almacenamiento para la gestión de datos de ONTAP. Muchos de estos términos también se aplican a otros recopiladores de datos.



=== Reducida

* Model: Una lista delimitada por comas de los nombres de modelo de nodos discretos únicos dentro de este clúster. Si todos los nodos de los clústeres tienen el mismo tipo de modelo, solo aparecerá un nombre de modelo.
* Proveedor: El mismo nombre de proveedor que se vería si estuviera configurando un nuevo origen de datos.
* Número de serie: El UUID de la cabina
* IP: Generalmente serán las IP o los hostname tal como están configurados en el origen de datos.
* Versión de microcódigo: Firmware.
* Capacidad bruta: Suma base 2 de todos los discos físicos del sistema, sin importar su función.
* Latencia: Representación de lo que experimentan las cargas de trabajo a las que se enfrentan el host, tanto en lecturas como escrituras. Idealmente, Cloud Insights está abasteciéndose este valor directamente, pero este no es a menudo el caso. En lugar de que la cabina ofrezca esta configuración, Cloud Insights suele realizar un cálculo ponderado por IOPS derivado de las estadísticas de los volúmenes internos individuales.
* Rendimiento: Agregado de volúmenes internos. Administración: Puede contener un hipervínculo para la interfaz de gestión del dispositivo. Creado mediante programación por el origen de datos de Cloud Insights como parte de los informes de inventario.




=== Pool de almacenamiento

* Almacenamiento: En qué cabina de almacenamiento vive este pool. Obligatorio.
* Tipo: Valor descriptivo de una lista de posibilidades enumeradas. La mayoría de las veces será “agregado” o “grupo RAID”.
* Nodo: Si la arquitectura de esta cabina de almacenamiento pertenece a un nodo de almacenamiento específico, su nombre se verá aquí como un hipervínculo a su propia página de destino.
* Utiliza Flash Pool – Sí/no valor – ¿este pool basado en SATA/SAS tiene SSD utilizados para la aceleración del almacenamiento en caché?
* Redundancia: Esquema de protección o nivel de RAID. RAID_DP es de doble paridad, RAID_TP es de triple paridad.
* Capacidad: Los valores aquí son los lógicos utilizados, la capacidad utilizable y la capacidad total lógica, así como el porcentaje utilizado en estos.
* Capacidad sobreasignada: Si se utilizan tecnologías de eficiencia, se asignó una suma total de capacidades de volumen o volumen interno mayores que la capacidad lógica del pool de almacenamiento, el valor del porcentaje será mayor que 0 %.
* Snapshot: Las capacidades Snapshot se utilizan y en total, si su arquitectura de pool de almacenamiento dedica parte de su capacidad a los segmentos, en exclusiva para los snapshots. Es probable que las configuraciones de ONTAP en MetroCluster lo muestren, mientras que otras configuraciones de ONTAP son menos.
* Aprovechamiento: Un valor de porcentaje que muestra el mayor porcentaje de ocupación de disco de cualquier disco que contribuye a la capacidad de este pool de almacenamiento. El uso de discos no tiene necesariamente una fuerte correlación con el rendimiento de las cabinas. El aprovechamiento puede ser elevado debido a la recompilación de discos, a actividades de deduplicación, etc. en ausencia de cargas de trabajo dirigidas por el host. Además, las implementaciones de replicación de muchas matrices pueden impulsar el uso del disco sin mostrar como volumen interno o carga de trabajo de volumen.
* IOPS: La suma de IOPS de todos los discos que contribuyen a la capacidad de este pool de almacenamiento. Rendimiento: La suma del rendimiento de todos los discos que contribuyen a la capacidad de este pool de almacenamiento.




=== Nodo de almacenamiento

* Almacenamiento: ¿De qué cabina de almacenamiento forma parte este nodo? Obligatorio.
* Partner de ALTA DISPONIBILIDAD: En las plataformas en las que un nodo se conmuta al nodo de respaldo uno y solo otro, normalmente se verá aquí.
* Estado: Estado del nodo. Solo disponible cuando la matriz está lo suficientemente sana para ser inventariada por una fuente de datos.
* Model: Nombre de modelo del nodo.
* Versión: Nombre de versión del dispositivo.
* Número de serie: El número de serie del nodo.
* Memoria: Memoria base 2 si está disponible.
* Uso: En ONTAP, se trata de un índice de tensión de la controladora de un algoritmo propio. Con cada encuesta de rendimiento, se informará de una cifra entre 0 y 100 % que es la más alta entre la contención de disco WAFL o el uso medio de CPU. Si observa un valor sostenido > 50 %, esto indica que el dimensionamiento es insuficiente: Puede ser que una controladora/nodo no sea lo suficientemente grande o no haya suficientes discos giratorios para absorber la carga de trabajo de escritura.
* IOPS: Se deriva directamente de las llamadas REST DE ONTAP del objeto del nodo.
* Latencia: Se deriva directamente de las llamadas DE REST DE ONTAP del objeto del nodo.
* Rendimiento: Se deriva directamente de las llamadas REST DE ONTAP del objeto del nodo.
* Procesadores: Número de CPU.




== Requisitos

A continuación se enumeran los requisitos para configurar y utilizar este recopilador de datos:

* Debe tener acceso a una cuenta de usuario con el nivel de acceso requerido. Tenga en cuenta que se requieren permisos de administrador si se crea un nuevo rol/usuario de REST.
* ONTAP versión 9.14.1 o posterior.
* Entre los detalles de la cuenta se incluye el nombre de usuario y la contraseña
* Requisitos del puerto: 443
* Permisos de cuenta:
+
** Funcionalmente, Cloud Insights realiza solicitudes de lectura, pero se requieren algunos permisos de escritura para que Cloud Insights se registre en la cabina ONTAP. Consulte <<a-note-about-permissions,Nota sobre los permisos>> a continuación.






== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP de administración de ONTAP | La dirección IP o el nombre de dominio completo del clúster de NetApp. Debe ser IP/FQDN de administración del clúster. 


| Nombre de usuario REST DE ONTAP | Nombre de usuario del clúster de NetApp 


| Contraseña REST DE ONTAP | Contraseña para el clúster de NetApp 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (mín.) | El valor predeterminado es 60 minutos. 


| Intervalo de sondeo de rendimiento (s) | El valor predeterminado es 60 segundos. 


| Recopilación avanzada de datos de contador | Seleccione esta opción para incluir datos de contador avanzado de ONTAP en sondeos. Activado de forma predeterminada. 


| Habilite la recogida de eventos de EMS | Seleccione esto para incluir los datos del evento de registro de ONTAP EMS. Activado de forma predeterminada. 


| Intervalo de sondeo de EMS (seg) | El valor predeterminado es 60 segundos. 
|===


== Métricas de potencia de ONTAP

Varios modelos de ONTAP proporcionan métricas de potencia para Cloud Insights que se pueden utilizar para supervisión o alertas. Las listas de modelos compatibles y no compatibles a continuación no son exhaustivas, pero deben proporcionar alguna orientación; en general, si un modelo está en la misma familia que uno de la lista, el soporte debe ser el mismo.

Modelos compatibles:

A200
A220
A250
A300
A320
A400
A700
A700s
A800
A900
C190
FAS2240-4
FAS2552
FAS2650
FAS2720
FAS2750
FAS8200
FAS8300
FAS8700
FAS9000

Modelos no admitidos:

FAS2620
FAS3250
FAS3270
FAS500f
FAS6280
FAS/AFF 8020
FAS/AFF 8040
FAS/AFF 8060
FAS/AFF 8080



== Una nota sobre los permisos

Dado que varios paneles de control ONTAP de Cloud Insights se basan en contadores ONTAP avanzados, debe mantener habilitado *Habilitar Recopilación Avanzada de Datos de Contador* en la sección de Configuración Avanzada del recopilador de datos.

Para crear una cuenta local para Cloud Insights en el nivel de clúster, inicie sesión en ONTAP con el nombre de usuario/contraseña del administrador de administración del clúster y ejecute los siguientes comandos en el servidor ONTAP:

. Antes de empezar, debe iniciar sesión en ONTAP con una cuenta _Administrator_ y _Diagnostic-level Commands_ deben estar habilitados.
. Recupere el nombre del Vserver del tipo _admin_. Utilizará este nombre en los comandos posteriores.
+
 vserver show -type admin
. Cree un rol mediante los siguientes comandos:
+
....
security login rest-role create -role {role name} -api /api -access readonly
security login rest-role create -role {role name} -api /api/cluster/agents -access all
vserver services web access create -name spi -role {role name} -vserver {vserver name as retrieved above}
security login create -user-or-group-name {username} -application http -authentication-method password -role {role name}
....
. Cree el usuario de solo lectura mediante el comando siguiente. Una vez ejecutado el comando create, se le pedirá que introduzca una contraseña para este usuario.
+
 security login create -username ci_user -application http -authentication-method password -role ci_readonly


Si se utiliza la cuenta AD/LDAP, el comando debería ser

 security login create -user-or-group-name DOMAIN\aduser/adgroup -application http -authentication-method domain -role ci_readonly
El rol y el inicio de sesión de usuario resultantes tendrán algo parecido a lo siguiente. Su salida real puede variar:

[listing]
----
security login rest-role show -vserver <vserver name> -role restRole

               Role                                    Access
Vserver        Name            API                     Level
----------     -------------   -------------------     ------
<vserver name> restRole        /api                    readonly
                               /api/cluster/agents     all
2 entries were displayed.

security login show -vserver <vserver name> -user-or-group-name restUser

Vserver: <vserver name>
                                                                 Second
User/Group                 Authentication                 Acct   Authentication
Name           Application Method        Role Name        Locked Method
-------------- ----------- ------------- ---------------- ------ --------------
restUser       http        password      restRole         no     none
----


== Resolución de problemas

Algunas cosas para intentar si tiene problemas con este recopilador de datos:

[cols="2*"]
|===
| Problema: | Pruebe lo siguiente: 


| Al intentar crear un recopilador de DATOS REST DE ONTAP, se muestra un error como el siguiente:
Configuración: 10.193.70.14: La API REST de ONTAP en 10.193.70.14 no está disponible: 10.193.70.14 no se pudo OBTENER /api/cluster: 400 Solicitud incorrecta | Esto probablemente se deba a una cabina ONTAP más antigua, por ejemplo, ONTAP 9,6), que no tiene funcionalidades de API DE REST. ONTAP 9.14.1 es la versión de ONTAP mínima admitida por el recopilador de REST DE ONTAP. Se deben esperar respuestas de «Solicitud incorrecta de 400» en versiones de ONTAP previas a LA REST.

Para las versiones de ONTAP que admiten REST pero que no son 9.14.1 o posteriores, puede que aparezca el siguiente mensaje similar:
Configuración: 10.193.98.84: ONTAP REST API en 10.193.98.84 no está disponible: 10.193.98.84: ONTAP REST API en 10.193.98.84 está disponible: cheryl5-cluster-2 9.10.1 a3cb3247-3d3c-11ee-8ff3-005056b364a7 pero no es de la versión mínima 9.14.1. 


| Veo métricas vacías o «0» donde el recopilador de ontapi de ONTAP muestra datos. | ONTAP REST no informa sobre métricas que se utilizan internamente en el sistema ONTAP únicamente. Por ejemplo, ONTAP REST no recopilará agregados del sistema, solo se recopilarán las SVM de tipo «datos». 
|===
Puede encontrar información adicional en link:concept_requesting_support.html["Soporte técnico"] o en la link:reference_data_collector_support_matrix.html["Matriz de compatibilidad de recopilador de datos"].
