---
sidebar: sidebar 
permalink: task_kubernetes_operator_proxy.html 
keywords: telegraf, installation, install, agent, telegraf agent 
summary: 'Compatibilidad con Cloud Insights link:https://docs.influxdata.com/telegraf/v1.19/["Telegraf"] Como su agente para la recopilación de datos de integración y puede configurarse en Windows, Linux, MacOS y Kubernetes.' 
---
= Configuración de un agente para recopilar datos
:allow-uri-read: 


[role="lead"]
Uso de un repositorio de Docker personalizado/privado Configuración de un proxy Se puede configurar Un proxy para el operador de supervisión de la CR a partir del despliegue de CI que entró en producción el 10 de diciembre de 2021 10 de diciembre de 2021

kubectl -n netapp-monitoring agent-monitoring-netapp

En la sección SPEC: De este archivo, agregue el siguiente bloque de código

Espec: Proxy: IsAuProxyEnabled: <true or false> isTelegrafProxyEnabled: <true or false> isFluentbitProxyEnabled: <true or false> password: <password for proxy, optional> Port: <port for proxy> Server: <server for proxy> username: <username for proxy, optional> noProxy: <comma separated list of IPs or resolvable hostnames that should bypass a proxy> que utiliza un repositorio de Docker personalizado/privado obtiene el secreto del Docker

kubectl -n la supervisión de netapp obtiene el docker secreto -o ylma

(Copy paste el valor de .dockerconfigjson: En el resultado del comando anterior) descodifica el secreto de los Docker

Echo <paste from step #1 above> | base64 -d el resultado de esto será en el siguiente formato json: { "autos": {"docker.<cluster>.cloudinsights.netapp.com" : {"username":"<tenant id>", "password":"<password which is the CI API key>", "auth" :"<encoded username:password basic auth key. Esto es interno para docker>"} } } Inicio de sesión en el repositorio docker

docker login docker.<cluster>.cloudinsights.netapp.com (desde el paso 2) -u <username from step #2> contraseña: <password from step #2> extrae la imagen del operador docker de Cloud Insights

docker pull docker.<cluster>.cloudinsights.netapp.com/netapp-monitoring:<version>

Busque el campo <version> con el comando siguiente:

kubectl -n la supervisión de netapp consigue operadores de supervisión de la puesta en marcha | grep "imagen:" empuje la imagen del operador docker hacia su registro de dockers privado/empresarial

Inserte el código en su repositorio de Docker privado/local/empresarial de acuerdo con sus políticas corporativas Descargue todas las dependencias de código abierto a su registro de docker privado

Es necesario descargar las siguientes imágenes de código abierto: docker.io/telegraf:1.19.3 gcr.io/kubebuilder/kube-rbac-proxy:v0.0 k8s.gcr.io/kube-state-Metrics/kube-state-Metrics:v2.1.0

Si está habilitado el bit fluente: docker.io/fluent-bit:1.7.8 docker.io/kubernetes-event-exporter:0.10 edite el agente CR para reflejar la nueva ubicación del repo del docker, desactive la actualización automática (si está activada)

kubectl -n netapp-monitoring agent-monitoring-netapp

EnableAutoUpgrade: False docker-repo: <docker repo of the enterprise/corp docker repo> dockerRepoSecret: <optional: Nombre del secreto docker de Enterprise/corp docker repo, este secreto ya debería crearse en el clúster k8s en el mismo espacio de nombres>

En la sección SPEC:, realice los siguientes cambios:

espec.: telegraf: - nombre: sustitución ksm: - clave: k8s.gcr.io valor: <same as "docker-repo" field above>
