---
sidebar: sidebar 
permalink: telegraf_agent_k8s_config_options.html 
keywords: telegraf, installation, install, agent, telegraf agent, kubernetes, eks, operator, k8s, options, configuration 
summary: El operador de supervisión de Kubernetes de NetApp tiene una serie de opciones configurables. 
---
= Opciones de configuración del operador de supervisión de Kubernetes
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:nofooter: 
:toclevels: 2
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
La link:task_config_telegraf_agent_k8s.html#configuringcustomizing-the-operator["Operador de supervisión de Kubernetes"] la configuración se puede personalizar.

La siguiente tabla enumera las posibles opciones para el archivo _AgentConfiguration_:

[cols="1,1,2"]
|===
| Componente | Opción | Descripción 


| agente |  | Opciones de configuración comunes a todos los componentes que el operador puede instalar. Estas pueden considerarse como opciones “globales”. 


|  | Repositorio de documentos | Una anulación de dockerRepo para extraer imágenes de los repositorios de docker privados de los clientes en comparación con el repositorio de docker de Cloud Insights. El valor predeterminado es el repositorio de Cloud Insights docker 


|  | DockerImagePullSecret | Opcional: Un secreto para el repositorio privado de los clientes 


|  | Nombre del clúster | Campo de texto libre que identifica de forma única un clúster en todos los clústeres de clientes. Debe ser único en un cliente Cloud Insights. El valor predeterminado es lo que introduce el cliente en la interfaz de usuario del campo «Cluster Name» 


|  | proxy

Formato:

proxy:

  servidor:
  puerto:
  nombre de usuario:
  contraseña:
  NoProxy:
  IsTelegrafProxyActivado:
  Se habilita isAuProxyEnabled:
  IsFluentbitProxyEnabled:
  IsCollectorProxyEnabled: | Opcional para establecer el proxy. Este suele ser el proxy corporativo del cliente. 


| telegraf |  | Opciones de configuración que pueden personalizar la instalación de telegraf del Operador 


|  | Intervalo de colección | Intervalo de recopilación de métricas, en segundos (Max=60s) 


|  | DsCpuLimit | Límite de CPU para telegraf ds 


|  | DsMemLimit | Límite de memoria para telegraf ds 


|  | DsCpuRequest | Solicitud de CPU para telegraf ds 


|  | DsMemRequest | Solicitud de memoria para telegraf ds 


|  | RsCpuLimit | Límite de CPU para telegraf rs 


|  | RsMemLimit | Límite de memoria para telegraf rs 


|  | RsCpuRequest | Solicitud de CPU para telegraf rs 


|  | RsMemRequest | Solicitud de memoria para telegraf rs 


|  | Privilegios de ejecución | Ejecute el contenedor de telegraf en modo con privilegios. Establezca esta opción en true si SELinux está activado en los nodos k8s 


|  | Tamaño de lote | Consulte link:https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent["Documentación de configuración de Telegraf"] 


|  | Buffer Limit | Consulte link:https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent["Documentación de configuración de Telegraf"] 


|  | RoundInterval | Consulte link:https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent["Documentación de configuración de Telegraf"] 


|  | Colección Jitter | Consulte link:https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent["Documentación de configuración de Telegraf"] 


|  | precisión | Consulte link:https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent["Documentación de configuración de Telegraf"] 


|  | FlushInterval | Consulte link:https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent["Documentación de configuración de Telegraf"] 


|  | FlushJitter | Consulte link:https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent["Documentación de configuración de Telegraf"] 


|  | Tiempo de espera de salida | Consulte link:https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent["Documentación de configuración de Telegraf"] 


|  | DsToleraciones | telegraf-ds toleraciones adicionales. 


|  | RsToleraciones | toleraciones adicionales de telegraf-rs. 


|  | SkipLockedMemory | Vea esto link:https://community.influxdata.com/t/updating-telegraf-to-version-1-29-5-crashes-kubernetes-pod/33376["Problema conocido de Telegraf"].  Si se establece skipLockedMemory, se indicará al operador de supervisión de Kubernetes que ejecute Telegraf con el `--unprotected` bandera. 


| métricas-estado-kube |  | Opciones de configuración que pueden personalizar la instalación de métricas de estado kube del Operador 


|  | CpuLimit | Límite de CPU para la implementación de métricas de estado-kube 


|  | MemLimit | Límite de MEM para el despliegue de métricas de estado-kube 


|  | CpuRequest | Solicitud de CPU para el despliegue de métricas de estado de kube 


|  | MemRequest | Solicitud de MEM para el despliegue de métricas de estado de kube 


|  | recursos | lista separada por comas de recursos que se van a capturar. ejemplo: cronjobs,daemonsets,despliegues,ingresa,jobs,namespaces,nodos,persistentvolumeclaims, persistentvolumes,pods,replicasets,resourcequota,servicios,statefulsets 


|  | toleraciones | kube-state-metrics toleraciones adicionales. 


|  | etiquetas | lista separada por comas de recursos que kube-state-metrics debe capturar

+++
ejemplo: cronjobs=[*],daemonsets=[*],despliegues=[*],ingresses=[*],jobs=[*],namespaces=[*],nodes=[*],
persistentvolumeclaims=[*],persistentvolumes=[*],pods=[*],replicasets=[*],resourcequota=[*],services=[*],statefulsets=[*]
+++ 


| registros |  | Opciones de configuración que pueden personalizar la recopilación de registros y la instalación del operador 


|  | ReadFromHead | verdadero/falso, debe leer con fluidez el log de la cabecera 


|  | tiempo de espera | timeout, en segundos 


|  | DnsMode | TCP/UDP, modo para DNS 


|  | toleraciones de bits fluidas | toleraciones adicionales de fluent-bit-ds. 


|  | toleraciones-exportador-de-eventos | toleraciones adicionales de evento-exportador. 


|  | Event-exporter-maxEventAgeSeconds | antigüedad máxima de evento de exportador-evento.  Consulte https://github.com/jkroepke/resmoio-kubernetes-event-exporter[] 


| asignación de carga de trabajo |  | Opciones de configuración que pueden personalizar la recopilación de mapas de carga de trabajo y la instalación del operador 


|  | CpuLimit | Límite de CPU para ds de observador neto 


|  | MemLimit | límite de mem para ds de observador neto 


|  | CpuRequest | Solicitud de CPU para ds de observador de red 


|  | MemRequest | solicitud de mem para ds de observador neto 


|  | MetricAggregationInterval | intervalo de agregación de métricas, en segundos 


|  | BpfPollInterval | Intervalo de sondeo de BPF, en segundos 


|  | Habilitar DNSLookup | True/false, active la búsqueda de DNS 


|  | l4-toleraciones | net-observer-l4-ds toleraciones adicionales. 


|  | Privilegios de ejecución | True/false - Establece runPrivileged en true si SELinux está habilitado en los nodos de Kubernetes. 


| gestión del cambio |  | Opciones de configuración para la administración y análisis de cambios de Kubernetes 


|  | CpuLimit | Límite de CPU para change-observer-watch-rs 


|  | MemLimit | Límite de MEM para change-observer-watch-rs 


|  | CpuRequest | Solicitud de CPU para change-observer-watch-rs 


|  | MemRequest | solicitud de mem para change-observer-watch-rs 


|  | FailureDeclarationIntervalMins | Intervalo en minutos tras el cual un despliegue incorrecto de una carga de trabajo se marcará como erróneo 


|  | DeployAggrIntervalSeconds | Frecuencia a la que se envían los eventos de implementación de carga de trabajo en curso 


|  | No WorkloadAggrIntervalSeconds | Frecuencia a la que se combinan y se envían las implementaciones sin cargas de trabajo 


|  | TermsToRedact | Un conjunto de expresiones regulares utilizadas en los nombres de env y los mapas de datos cuyo valor será redactado
Términos de ejemplo: “Pwd”, “password”, “token”, “apikey”, “api-key”, jwt 


|  | KindsToWatch adicional | Una lista separada por comas de tipos adicionales para ver desde el conjunto predeterminado de tipos observados por el recopilador 


|  | KindsToIgnoreFromWatch | Una lista separada por comas de tipos que ignorar de la observación del conjunto predeterminado de tipos observados por el recopilador 


|  | LogRecordAggrIntervalSeconds | Frecuencia con la que los registros de registro se envían a CI desde el recopilador 


|  | toleraciones de vigilancia | tolerancia adicional change-observer-watch-ds. Formato de línea única abreviado solamente.
Ejemplo: '{key: taint1, operator: Exists, effect: NoSchedule},{key: taint2, operator: Exists, effect: Noexecute}' 
|===


== Archivo de configuración de AgentConfiguration de ejemplo

A continuación se muestra un archivo _AgentConfiguration_ de ejemplo.

[listing]
----
apiVersion: monitoring.netapp.com/v1alpha1
kind: AgentConfiguration
metadata:
  name: netapp-monitoring-configuration
  namespace: "NAMESPACE_PLACEHOLDER"
  labels:
    installed-by: nkmo-NAMESPACE_PLACEHOLDER

spec:
  # # You can modify the following fields to configure the operator.
  # # Optional settings are commented out and include default values for reference
  # #   To update them, uncomment the line, change the value, and apply the updated AgentConfiguration.
  agent:
    # # [Required Field] A uniquely identifiable user-friendly clustername.
    # # clusterName must be unique across all clusters in your Cloud Insights environment.
    clusterName: "CLUSTERNAME_PLACEHOLDER"

    # # Proxy settings. The proxy that the operator should use to send metrics to Cloud Insights.
    # # Please see documentation here: https://docs.netapp.com/us-en/cloudinsights/task_config_telegraf_agent_k8s.html#configuring-proxy-support
    # proxy:
    #   server:
    #   port:
    #   noproxy:
    #   username:
    #   password:
    #   isTelegrafProxyEnabled:
    #   isFluentbitProxyEnabled:
    #   isCollectorsProxyEnabled:

    # # [Required Field] By default, the operator uses the CI repository.
    # # To use a private repository, change this field to your repository name.
    # # Please see documentation here: https://docs.netapp.com/us-en/cloudinsights/task_config_telegraf_agent_k8s.html#using-a-custom-or-private-docker-repository
    dockerRepo: 'DOCKER_REPO_PLACEHOLDER'
    # # [Required Field] The name of the imagePullSecret for dockerRepo.
    # # If you are using a private repository, change this field from 'docker' to the name of your secret.
    {{ if not (contains .Values.config.cloudType "aws") }}# {{ end -}}
    dockerImagePullSecret: 'docker'

    # # Allow the operator to automatically rotate its ApiKey before expiration.
    # tokenRotationEnabled: '{{ .Values.telegraf_installer.kubernetes.rs.shim_token_rotation  }}'
    # # Number of days before expiration that the ApiKey should be rotated. This must be less than the total ApiKey duration.
    # tokenRotationThresholdDays: '{{ .Values.telegraf_installer.kubernetes.rs.shim_token_rotation_threshold_days  }}'

  telegraf:
    # # Settings to fine-tune metrics data collection. Telegraf config names are included in parenthesis.
    # # See https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent

    # # The default time telegraf will wait between inputs for all plugins (interval). Max=60
    # collectionInterval: '{{ .Values.telegraf_installer.agent_resources.collection_interval }}'
    # # Maximum number of records per output that telegraf will write in one batch (metric_batch_size).
    # batchSize: '{{ .Values.telegraf_installer.agent_resources.metric_batch_size }}'
    # # Maximum number of records per output that telegraf will cache pending a successful write (metric_buffer_limit).
    # bufferLimit: '{{ .Values.telegraf_installer.agent_resources.metric_buffer_limit }}'
    # # Collect metrics on multiples of interval (round_interval).
    # roundInterval: '{{ .Values.telegraf_installer.agent_resources.round_interval }}'
    # # Each plugin waits a random amount of time between the scheduled collection time and that time + collection_jitter before collecting inputs (collection_jitter).
    # collectionJitter: '{{ .Values.telegraf_installer.agent_resources.collection_jitter }}'
    # # Collected metrics are rounded to the precision specified. When set to "0s" precision will be set by the units specified by interval (precision).
    # precision: '{{ .Values.telegraf_installer.agent_resources.precision }}'
    # # Time telegraf will wait between writing outputs (flush_interval). Max=collectionInterval
    # flushInterval: '{{ .Values.telegraf_installer.agent_resources.flush_interval }}'
    # # Each output waits a random amount of time between the scheduled write time and that time + flush_jitter before writing outputs (flush_jitter).
    # flushJitter: '{{ .Values.telegraf_installer.agent_resources.flush_jitter }}'
    # # Timeout for writing to outputs (timeout).
    # outputTimeout: '{{ .Values.telegraf_installer.http_output_plugin.timeout }}'

    # # telegraf-ds CPU/Mem limits and requests.
    # # See https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
    dsCpuLimit: '{{ .Values.telegraf_installer.telegraf_resources.ds_cpu_limits  }}'
    dsMemLimit: '{{ .Values.telegraf_installer.telegraf_resources.ds_mem_limits  }}'
    dsCpuRequest: '{{ .Values.telegraf_installer.telegraf_resources.ds_cpu_request  }}'
    dsMemRequest: '{{ .Values.telegraf_installer.telegraf_resources.ds_mem_request  }}'

    # # telegraf-rs CPU/Mem limits and requests.
    rsCpuLimit: '{{ .Values.telegraf_installer.telegraf_resources.rs_cpu_limits  }}'
    rsMemLimit: '{{ .Values.telegraf_installer.telegraf_resources.rs_mem_limits  }}'
    rsCpuRequest: '{{ .Values.telegraf_installer.telegraf_resources.rs_cpu_request  }}'
    rsMemRequest: '{{ .Values.telegraf_installer.telegraf_resources.rs_mem_request  }}'

    # # telegraf additional tolerations. Use the following abbreviated single line format only.
    # # Inspect telegraf-rs/-ds to view tolerations which are always present.
    # # Example: '{key: taint1, operator: Exists, effect: NoSchedule},{key: taint2, operator: Exists, effect: NoExecute}'
    # dsTolerations: ''
    # rsTolerations: ''

    # # Set runPrivileged to true if SELinux is enabled on your Kubernetes nodes.
    # runPrivileged: 'false'

    # # Collect NFS IO metrics.
    # dsNfsIOEnabled: '{{ .Values.telegraf_installer.kubernetes.ds.shim_nfs_io_processing }}'

    # # Collect kubernetes.system_container metrics and objects in the kube-system|cattle-system namespaces for managed kubernetes clusters (EKS, AKS, GKE, managed Rancher).  Set this to true if you want collect these metrics.
    # managedK8sSystemMetricCollectionEnabled: '{{ .Values.telegraf_installer.kubernetes.shim_managed_k8s_system_metric_collection }}'

    # # Collect kubernetes.pod_volume (pod ephemeral storage) metrics.  Set this to true if you want to collect these metrics.
    # podVolumeMetricCollectionEnabled: '{{ .Values.telegraf_installer.kubernetes.shim_pod_volume_metric_collection }}'

    # # Declare Rancher cluster as managed.  Set this to true if your Rancher cluster is managed as opposed to on-premise.
    # isManagedRancher: '{{ .Values.telegraf_installer.kubernetes.is_managed_rancher }}'

  # kube-state-metrics:
    # # kube-state-metrics CPU/Mem limits and requests. By default, when unset, kube-state-metrics has no CPU/Mem limits nor request.
    # cpuLimit:
    # memLimit:
    # cpuRequest:
    # memRequest:

    # # Comma-separated list of metrics to enable.
    # # See metric-allowlist in https://github.com/kubernetes/kube-state-metrics/blob/main/docs/cli-arguments.md
    # resources: 'cronjobs,daemonsets,deployments,ingresses,jobs,namespaces,nodes,persistentvolumeclaims,persistentvolumes,pods,replicasets,resourcequotas,services,statefulsets'

    # # Comma-separated list of Kubernetes label keys that will be used in the resources' labels metric.
    # # See metric-labels-allowlist in https://github.com/kubernetes/kube-state-metrics/blob/main/docs/cli-arguments.md
    # labels: 'cronjobs=[*],daemonsets=[*],deployments=[*],ingresses=[*],jobs=[*],namespaces=[*],nodes=[*],persistentvolumeclaims=[*],persistentvolumes=[*],pods=[*],replicasets=[*],resourcequotas=[*],services=[*],statefulsets=[*]'

    # # kube-state-metrics additional tolerations. Use the following abbreviated single line format only.
    # # No tolerations are applied by default
    # # Example: '{key: taint1, operator: Exists, effect: NoSchedule},{key: taint2, operator: Exists, effect: NoExecute}'
    # tolerations: ''

  # # Settings for the Events Log feature.
  # logs:
    # # If Fluent Bit should read new files from the head, not tail.
    # # See Read_from_Head in https://docs.fluentbit.io/manual/pipeline/inputs/tail
    # readFromHead: "true"

    # # Network protocol that Fluent Bit should use for DNS: "UDP" or "TCP".
    # dnsMode: "UDP"

    # # Logs additional tolerations. Use the following abbreviated single line format only.
    # # Inspect fluent-bit-ds to view tolerations which are always present. No tolerations are applied by default for event-exporter.
    # # Example: '{key: taint1, operator: Exists, effect: NoSchedule},{key: taint2, operator: Exists, effect: NoExecute}'
    # fluent-bit-tolerations: ''
    # event-exporter-tolerations: ''

    # # event-exporter max event age.
    # # See https://github.com/jkroepke/resmoio-kubernetes-event-exporter
    # event-exporter-maxEventAgeSeconds: '10'

  # # Settings for the Network Performance and Map feature.
  # workload-map:
    # # net-observer-l4-ds CPU/Mem limits and requests.
    # # See https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
    # cpuLimit: '500m'
    # memLimit: '500Mi'
    # cpuRequest: '100m'
    # memRequest: '500Mi'

    # # Metric aggregation interval in seconds. Min=30, Max=120
    # metricAggregationInterval: '60'

    # # Interval for bpf polling. Min=3, Max=15
    # bpfPollInterval: '8'

    # # Enable performing reverse DNS lookups on observed IPs.
    # enableDNSLookup: 'true'

    # # net-observer-l4-ds additional tolerations. Use the following abbreviated single line format only.
    # # Inspect net-observer-l4-ds to view tolerations which are always present.
    # # Example: '{key: taint1, operator: Exists, effect: NoSchedule},{key: taint2, operator: Exists, effect: NoExecute}'
    # l4-tolerations: ''

    # # Set runPrivileged to true if SELinux is enabled on your Kubernetes nodes.
    # # Note: In OpenShift environments, this is set to true automatically.
    # runPrivileged: 'false'

  # change-management:
    # # change-observer-watch-rs CPU/Mem limits and requests.
    # # See https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
    # cpuLimit: '500m'
    # memLimit: '500Mi'
    # cpuRequest: '100m'
    # memRequest: '500Mi'

    # # Interval in minutes after which a non-successful deployment of a workload will be marked as failed
    # failureDeclarationIntervalMins: '30'

    # # Frequency at which workload deployment in-progress events are sent
    # deployAggrIntervalSeconds: '300'

    # # Frequency at which non-workload deployments are combined and sent
    # nonWorkloadAggrIntervalSeconds: '15'

    # # A set of regular expressions used in env names and data maps whose value will be redacted
    # termsToRedact: '"pwd", "password", "token", "apikey", "api-key", "api_key", "jwt", "accesskey", "access_key", "access-key", "ca-file", "key-file", "cert", "cafile", "keyfile", "tls", "crt", "salt", ".dockerconfigjson", "auth", "secret"'

    # # A comma separated list of additional kinds to watch from the default set of kinds watched by the collector
    # # Each kind will have to be prefixed by its apigroup
    # # Example: '"authorization.k8s.io.subjectaccessreviews"'
    # additionalKindsToWatch: ''

    # # A comma separated list of kinds to ignore from watching from the default set of kinds watched by the collector
    # # Each kind will have to be prefixed by its apigroup
    # # Example: '"networking.k8s.io.networkpolicies","batch.jobs"'
    # kindsToIgnoreFromWatch: ''


    # # Frequency with which log records are sent to CI from the collector
    # logRecordAggrIntervalSeconds: '20'

    # # change-observer-watch-ds additional tolerations. Use the following abbreviated single line format only.
    # # Inspect change-observer-watch-ds to view tolerations which are always present.
    # # Example: '{key: taint1, operator: Exists, effect: NoSchedule},{key: taint2, operator: Exists, effect: NoExecute}'
    # watch-tolerations: ''

----